name: yarn Build and Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      fetch-depth:
        default: 0
        required: false
        type: number

      node-version:
        default: latest
        required: false
        type: string

      yarn-version:
        default: latest
        required: false
        type: string

      cname:
        required: false
        type: string

      publish_dir:
        required: false
        type: string
        
      build_command:
        default: yarn build
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn
      - name: Build
        run: ${{ inputs.build_command }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.publish_dir }}
          cname: ${{ inputs.cname }}
