---
# This workflow will release the packages with Changesets

name: 🚀 CI - publish

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js and npm config
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@valiantlynx'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build && npm run package

      - name: Configure .npmrc for Publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # Ensure you have a script in your package.json named "release" that is configured for npm.
          # This could simply be: "release": "npm publish --access public" or include the changeset publish command as needed.
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
