---
# This workflow will release the packages with Changesets

name: 🚀 CI - publish

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js and npm config
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@valiantlynx'
          node-auth-token: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build && yarn package

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The NPM_TOKEN is now only necessary if the publish script or any other step explicitly requires it,
          # but the setup-node action has already configured npm authentication globally for this job.
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}