---
name: issues

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
    post_discord_message:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              working-directory: packages/scripts/python
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run script
              working-directory: packages/scripts/python
              run: |
                    issue_data='{"title": "${{ github.event.issue.title }}", "body": "${{ github.event.issue.body }}", "user": "${{ github.event.issue.user.login }}", "avatar_url": "${{ github.event.issue.user.avatar_url }}", "html_url": "${{ github.event.issue.html_url }}"}'
                    python main.py issue_discord_message "$issue_data" "${{ github.event.action }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

